[package]
name = "Tugboat"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
futures = "0.3.31"
ratatui = "0.29.0"
shiplift = "0.7.0"
strip-ansi-escapes = "0.2.1"
tokio = { version = "1", features = ["full"]}
